---

- name: SETUP VLAN INTERFACES
  template: src=vlaninterface.j2 dest=/home/jullrich/var/virl-lab/cfg/{{ inventory_hostname }}_svi.conf
  with_items: dl-cl-switch
  register: result

- name: PUSH INTERFACE CONFIGURATION
  ntc_config_command:
    connection: ssh
    platform: cisco_ios
    commands_file: "/home/jullrich/var/virl-lab/cfg/{{ inventory_hostname }}_svi.conf"
    host: "{{ ansible_host }}"
    username: "{{ username }}"
    password: "{{ password }}"
    secret: "{{ secret }}"
  register: result
