---
- name: Replace config with init configuration
  hosts: all
  connection: local
  gather_facts: no

  tasks:
  - name: Push init configuration with napalm
    napalm_install_config:
        hostname={{hostname}}
        username={{user}}
        dev_os={{os}}
        password={{passwd}}
        config_file={{config_dir}}/{{hostname}}/init.conf
        commit_changes=True
        replace_config=True
        diff_file={{config_dir}}/{{hostname}}/init.diff
