---

- name: Merge ipsec configuration
  hosts: rtr
  connection: local
  gather_facts: no

  tasks:
  - name: Push ipsec configuration with napalm
    napalm_install_config:
        hostname={{inventory_hostname}}
        username={{username}}
        dev_os={{os}}
        password={{password}}
        config_file={{config_dir}}/{{inventory_hostname}}/ipsec.conf
        commit_changes=True
        replace_config=False
        diff_file={{config_dir}}/{{inventory_hostname}}/ipsec.diff
