---
- name: Merge glbp configuration
  hosts: glbp
  connection: local
  gather_facts: no

  tasks:
  - name: Push glbp configuration with napalm
    napalm_install_config:
        hostname={{inventory_hostname}}
        username={{username}}
        dev_os="ios"
        password={{password}}
        config_file={{config_dir}}/{{inventory_hostname}}/glbp.conf
        commit_changes=True
        replace_config=True
        get_diffs=True
        diff_file={{config_dir}}/{{inventory_hostname}}/glbp.diff
