---
- name: Generate base config
  hosts: all
  gather_facts: no
  connection: local

  # Verzeichnisse werden mit init angelegt
  # pre_tasks:
  #   #- name: remove potentially existing previous candidate config directories
  #   #  file: path={{config_dir}}/{{ inventory_hostname}} state=absent
  #   - name: create candidate config directory
  #     file: path={{config_dir}}/{{ inventory_hostname}} state=directory

  roles:
  - base-config
