---
- name: Generate ipsec config
  hosts: tunnel
  gather_facts: no
  connection: local

  # pre_tasks:
  #   #- name: remove potentially existing previous candidate config directories
  #   #  file: path={{config_dir}}/{{ inventory_hostname}} state=absent
  #   - name: create candidate config directory
  #     file: path={{config_dir}}/{{ inventory_hostname}} state=directory

    #- name: include tunnels
    #  include: ./group_vars/tunnels.yml

  roles:
  - ipsec
