---

- name: get vlans
  hosts: switch
  connection: local
  gather_facts: False

  tasks:

    - name: get ...
      ntc_show_command:
        connection: ssh
        platform: cisco_ios
        command: "show vlan"
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        secret: "{{ secret }}"
      register: result

    - debug: var=result
