---

- name: Lab sichern
  hosts: all
  connection: local
  gather_facts: False

  tasks:

    - name: get configs
      ntc_save_config:
        platform: cisco_ios_ssh
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        secret: "{{ secret }}"
        local_file: cfg/{{ inventory_hostname }}/running-config.cfg
