---

- name: get facts
  hosts: rtr
  connection: local
  gather_facts: False

  tasks:
    - name: get facts
      ntc_get_facts:
        platform: cisco_ios_ssh
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        secret: "{{ secret }}"
        # dev_os: "{{ dev_os }}"
        # dev_os: "ios"
        # config_file: initial.conf
        # commit_changes: False
        # replace_config: True
        # diff_file: initial.diff
        # filter: 'environment'
      register: result

    - name: print data
      debug: var=result
